ARG NODE_VERSION=21.6.0

FROM node:${NODE_VERSION}-alpine AS base

WORKDIR /app

COPY . .

RUN corepack enable

RUN corepack prepare pnpm@latest --activate

RUN pnpm install


CMD ["pnpm", "run", "start:dev"]
