services:
  bot_service:
    restart: always
    ports:
      - "${PORT}:${PORT}"
    build:
      context: .
      dockerfile: ${DOCKERFILE_PATH}
    env_file:
      - .env
    volumes:
      - ./src/:/app/src
