export const TELEGRAM_PROVIDER = Symbol('TELEGRAM_BOT_PROVIDER');
export const CLASS_NOTIFICATION_BOT_PROVIDER = Symbol(
  'CLASS_NOTIFICATION_BOT_PROVIDER',
);
export const TELEGRAM_REMEMBER_REDMINE_BOT_PROVIDER = Symbol(
  'TELEGRAM_REMEMBER_REDMINE_BOT_PROVIDER',
);
